//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Ticket_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Circus_Events Circus_Events { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
